name: Spring CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8.0
      - name: Test with Gradle
        run: ./gradlew test
